version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      assignees:
        - "mentalcaries"
        - "mxmason"
      reviewers:
        - "mentalcaries"
        - "mxmason"
