# Config file for enabling Dependabot to make weekly PRs against our NPM dependencies
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      assignees:
        - 'mentalcaries'
        - 'mxmason'
      reviewers:
        - 'mentalcaries'
        - 'mxmason'
