version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
        - "mentalcaries"
        - "mxmason"
    reviewers:
        - "mentalcaries"
        - "mxmason"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
